/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_TicTacToe;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Loginscreen extends javax.swing.JFrame {

    /**
     * Creates new form Loginscreen
     */
    public Loginscreen() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        start_btn.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        NameX = new javax.swing.JTextField();
        AgeX = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        Xerrormessage = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        NameO = new javax.swing.JTextField();
        AgeO = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Oerrormessage = new javax.swing.JLabel();
        start_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        backtoregister_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Age     : ");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 70));

        jLabel9.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PlayerX : ");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 70));

        jRadioButton5.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Chiller", 0, 35)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Male");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 90, 60));

        jRadioButton6.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Chiller", 0, 35)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Female");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 110, 60));

        jRadioButton7.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Chiller", 0, 35)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Other");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 130, 60));

        NameX.setBackground(new java.awt.Color(51, 51, 51));
        NameX.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        NameX.setForeground(new java.awt.Color(255, 255, 255));
        NameX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        NameX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameXActionPerformed(evt);
            }
        });
        NameX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameXKeyReleased(evt);
            }
        });
        jPanel4.add(NameX, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 250, 50));

        AgeX.setFont(new java.awt.Font("Chiller", 1, 25)); // NOI18N
        AgeX.setModel(new javax.swing.SpinnerNumberModel(3, 3, 100, 1));
        AgeX.setInheritsPopupMenu(true);
        jPanel4.add(AgeX, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 160, 50));

        jLabel10.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender  : ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 70));

        jLabel11.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Region  : ");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 70));

        jComboBox3.setFont(new java.awt.Font("Chiller", 1, 30)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chittagong", "Dhaka", "Khulna", "Rajshahi", "Barisal", "Sylhet", "Brahmanbaria", "Comilla", " " }));
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, 50));

        Xerrormessage.setFont(new java.awt.Font("Chiller", 1, 27)); // NOI18N
        Xerrormessage.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(Xerrormessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 410, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 710, 400));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PlayerO : ");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, 70));

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age     : ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 70));

        jLabel6.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender  : ");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 70));

        jRadioButton2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Chiller", 0, 35)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Male");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 80, 60));

        jRadioButton3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Chiller", 0, 35)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Female");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 100, 60));

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Chiller", 0, 35)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Other");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 130, 60));

        NameO.setBackground(new java.awt.Color(51, 51, 51));
        NameO.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        NameO.setForeground(new java.awt.Color(255, 255, 255));
        NameO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        NameO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameOActionPerformed(evt);
            }
        });
        NameO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameOKeyReleased(evt);
            }
        });
        jPanel5.add(NameO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 250, 50));

        AgeO.setFont(new java.awt.Font("Chiller", 1, 25)); // NOI18N
        AgeO.setModel(new javax.swing.SpinnerNumberModel(3, 3, 100, 1));
        AgeO.setInheritsPopupMenu(true);
        jPanel5.add(AgeO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 160, 50));

        jLabel8.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Region  : ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 70));

        jComboBox2.setFont(new java.awt.Font("Chiller", 1, 30)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chittagong", "Dhaka", "Khulna", "Rajshahi", "Barisal", "Sylhet", "Brahmanbaria", "Comilla", " " }));
        jPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, 50));

        Oerrormessage.setFont(new java.awt.Font("Chiller", 1, 27)); // NOI18N
        Oerrormessage.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(Oerrormessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 320, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 690, 400));

        start_btn.setBackground(new java.awt.Color(0, 0, 0));
        start_btn.setFont(new java.awt.Font("Chiller", 1, 80)); // NOI18N
        start_btn.setForeground(new java.awt.Color(255, 255, 255));
        start_btn.setText("START!");
        start_btn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Chiller", 1, 60))); // NOI18N
        start_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });
        jPanel3.add(start_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 220, 120));

        jLabel5.setFont(new java.awt.Font("Chiller", 1, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Register for a game!");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 581, 70));

        jCheckBox1.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setFont(new java.awt.Font("Chiller", 1, 25)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Do you agree to the terms and conditions?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        backtoregister_btn.setBackground(new java.awt.Color(0, 0, 0));
        backtoregister_btn.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        backtoregister_btn.setForeground(new java.awt.Color(255, 255, 255));
        backtoregister_btn.setText("◄");
        backtoregister_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backtoregister_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtoregister_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoregister_btnActionPerformed(evt);
            }
        });
        jPanel3.add(backtoregister_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 80, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1460, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1530, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameOActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void NameXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameXActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NameXActionPerformed
    
    
    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        // TODO add your handling code here:
        if (NameX.getText().trim().isEmpty() && NameO.getText().trim().isEmpty()){
            Xerrormessage.setText("PlayerX name required!!");
            Oerrormessage.setText("PlayerO name required!!");
        }
        else if (NameX.getText().trim().isEmpty()){
            Xerrormessage.setText("PlayerX name required!!");
        }
        else if (NameO.getText().trim().isEmpty()){
            Oerrormessage.setText("PlayerO name required!!");
        }
        else{
        Java_TicTacToe x = new Java_TicTacToe();
        Java_TicTacToe.PlayerX_ScoreLabel.setText(Loginscreen.NameX.getText());
        Java_TicTacToe.PlayerO_ScoreLabel.setText(Loginscreen.NameO.getText());
        
        x.show();
        
        dispose();
        }
    }//GEN-LAST:event_start_btnActionPerformed

    private void backtoregister_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoregister_btnActionPerformed
        // TODO add your handling code here:
        Titlescreen jf2 = new Titlescreen();
        jf2.show();

        dispose();
    }//GEN-LAST:event_backtoregister_btnActionPerformed

    private void NameXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameXKeyReleased
        // TODO add your handling code here:
        Xerrormessage.setText("");
    }//GEN-LAST:event_NameXKeyReleased

    private void NameOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameOKeyReleased
        // TODO add your handling code here:
        Oerrormessage.setText("");
    }//GEN-LAST:event_NameOKeyReleased

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()){
            start_btn.setEnabled(true);
        }
        if (!jCheckBox1.isSelected()){
            start_btn.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JSpinner AgeO;
    public static javax.swing.JSpinner AgeX;
    public static javax.swing.JTextField NameO;
    public static javax.swing.JTextField NameX;
    private javax.swing.JLabel Oerrormessage;
    private javax.swing.JLabel Xerrormessage;
    private javax.swing.JButton backtoregister_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JButton start_btn;
    // End of variables declaration//GEN-END:variables
}
