/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_TicTacToe;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Stats extends javax.swing.JFrame {

    /**
     * Creates new form Stats
     */
    public Stats() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backtogame_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        OWinPercentage = new javax.swing.JLabel();
        XWinPercentage = new javax.swing.JLabel();
        OName = new javax.swing.JLabel();
        OGamesWon = new javax.swing.JLabel();
        XName = new javax.swing.JLabel();
        XGamesWon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("\"Java Tic-Tac-Toe Game\"");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 820, 100));

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STATISTICS");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 450, 100));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Win Percentage(%)");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 230, 50));

        backtogame_btn.setBackground(new java.awt.Color(0, 0, 0));
        backtogame_btn.setFont(new java.awt.Font("Chiller", 0, 40)); // NOI18N
        backtogame_btn.setForeground(new java.awt.Color(255, 255, 255));
        backtogame_btn.setText("Return To Menu");
        backtogame_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backtogame_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtogame_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtogame_btnActionPerformed(evt);
            }
        });
        jPanel3.add(backtogame_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 220, 90));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 100, 50));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Chiller", 1, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Games Won");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 140, 50));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 190, 10));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 190, 10));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 110, 10));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 170, 10));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 170, 10));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 130, 10));

        OWinPercentage.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        OWinPercentage.setForeground(new java.awt.Color(255, 255, 255));
        OWinPercentage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OWinPercentage.setText("0%");
        jPanel3.add(OWinPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 160, 30));

        XWinPercentage.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        XWinPercentage.setForeground(new java.awt.Color(255, 255, 255));
        XWinPercentage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        XWinPercentage.setText("0%");
        jPanel3.add(XWinPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 150, 30));

        OName.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        OName.setForeground(new java.awt.Color(255, 255, 255));
        OName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OName.setText("OName");
        jPanel3.add(OName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 260, 30));

        OGamesWon.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        OGamesWon.setForeground(new java.awt.Color(255, 255, 255));
        OGamesWon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OGamesWon.setText("0");
        jPanel3.add(OGamesWon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 370, 100, 30));

        XName.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        XName.setForeground(new java.awt.Color(255, 255, 255));
        XName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        XName.setText("XName");
        jPanel3.add(XName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 220, 30));

        XGamesWon.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        XGamesWon.setForeground(new java.awt.Color(255, 255, 255));
        XGamesWon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        XGamesWon.setText("0");
        jPanel3.add(XGamesWon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 1390, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backtogame_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtogame_btnActionPerformed
        // TODO add your handling code here:
        Titlescreen jf2 = new Titlescreen();
        
        jf2.show();
        dispose();
    }//GEN-LAST:event_backtogame_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel OGamesWon;
    public static javax.swing.JLabel OName;
    public static javax.swing.JLabel OWinPercentage;
    public static javax.swing.JLabel XGamesWon;
    public static javax.swing.JLabel XName;
    public static javax.swing.JLabel XWinPercentage;
    private javax.swing.JButton backtogame_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
