/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_TicTacToe;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Titlescreen extends javax.swing.JFrame {

    /**
     * Creates new form Titlescreen
     */
    public Titlescreen() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        play_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        guest_btn = new javax.swing.JButton();
        about_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Chiller", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("All Rights Reserved by TP Studios");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 600, 300, 100));

        play_btn.setBackground(new java.awt.Color(0, 0, 0));
        play_btn.setFont(new java.awt.Font("Chiller", 1, 80)); // NOI18N
        play_btn.setForeground(new java.awt.Color(255, 255, 255));
        play_btn.setText("PLAY");
        play_btn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Chiller", 1, 60))); // NOI18N
        play_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        play_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_btnActionPerformed(evt);
            }
        });
        jPanel3.add(play_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 220, 120));

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("\"Java Tic-Tac-Toe Game\"");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 820, 100));

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("a java-based arcade game");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 450, 100));

        guest_btn.setBackground(new java.awt.Color(0, 0, 0));
        guest_btn.setFont(new java.awt.Font("Chiller", 1, 30)); // NOI18N
        guest_btn.setForeground(new java.awt.Color(255, 255, 255));
        guest_btn.setText("Guest!");
        guest_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guest_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guest_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guest_btnActionPerformed(evt);
            }
        });
        jPanel3.add(guest_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 100, 60));

        about_btn1.setBackground(new java.awt.Color(0, 0, 0));
        about_btn1.setFont(new java.awt.Font("Chiller", 1, 30)); // NOI18N
        about_btn1.setForeground(new java.awt.Color(255, 255, 255));
        about_btn1.setText("About");
        about_btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        about_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(about_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 90, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void play_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_btnActionPerformed
        // TODO add your handling code here:
        Loginscreen jf2 = new Loginscreen();
        jf2.show();

        dispose();
    }//GEN-LAST:event_play_btnActionPerformed

    private void guest_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guest_btnActionPerformed
        // TODO add your handling code here:
        
        Java_TicTacToe btn = new Java_TicTacToe();
        Java_TicTacToe.PlayerX_ScoreLabel.setText("GuestX");
        Java_TicTacToe.PlayerO_ScoreLabel.setText("GuestO");
        
        
        btn.show();

        dispose();
    }//GEN-LAST:event_guest_btnActionPerformed

    private void about_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_btn1ActionPerformed
        // TODO add your handling code here:
        About btn = new About();
        btn.show();

        dispose();
    }//GEN-LAST:event_about_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Titlescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Titlescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Titlescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Titlescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Titlescreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about_btn1;
    private javax.swing.JButton guest_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton play_btn;
    // End of variables declaration//GEN-END:variables
}
